name: schedule

on:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [fix-*]
  schedule:
    # Every 24 hours
    - cron: "20 */24 * * *"
    # Every day at 6am
    # - cron: "0 6 * * *"
  # allow run manually
  workflow_dispatch:

permissions: write-all


jobs:
  casks:
    name: Bump Casks in parallel
    if: github.repository == 'brewforge/homebrew-extras'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Homebrew env
        uses: ./.github/actions/homebrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump casks
        uses: ./.github/actions/bump-casks
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

  formulas:
    name: Bump Formulas in parallel
    if: github.repository == 'brewforge/homebrew-extras'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Homebrew env
        uses: ./.github/actions/homebrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      # - name: Bump formulas
      #   uses: ./.github/actions/bump-formulas
      #   with:
      #     HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
